# ╭──────────────────────────────────────────────────────────────────╮
# │                        Environment                               │
# ╰──────────────────────────────────────────────────────────────────╯

# Wayland Session
env = XDG_SESSION_TYPE, wayland
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_DESKTOP, Hyprland

# Cursor
env = XCURSOR_SIZE, 30
env = XCURSOR_THEME, catppuccin-latte-pink-cursors

# Wayland
env = MOZ_ENABLE_WAYLAND, 1
# env = WLR_NO_HARDWARE_CURSORS, 1

# Apps
env = NIXOS_OZONE_WL, 1
env = SPOTIFY_USE_WAYLAND, 1

# Qt Theming
env = QT_QPA_PLATFORMTHEME, qt6ct

# NVIDIA (uncomment if using NVIDIA GPU)
# env = LIBVA_DRIVER_NAME, nvidia
# env = GBM_BACKEND, nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME, nvidia
