font_family      JetBrainsMono Nerd Font
font_size        11.5
line_spacing     1.1
letter_spacing   0.5

# Fox ML background & foreground
background            #{{BG}}
foreground            #{{PRIMARY}}

cursor                #{{SECONDARY}}
selection_background  #{{SURFACE}}
selection_foreground  #{{FG}}

# Core Fox ML 16-color palette

color0  #{{BG}}
color1  #{{RED}}
color2  #{{GREEN}}
color3  #{{YELLOW}}
color4  #{{BLUE}}
color5  #{{SECONDARY}}
color6  #{{CYAN}}
color7  #{{FG}}

color8  #{{SURFACE}}
color9  #{{RED_BRIGHT}}
color10 #{{GREEN_BRIGHT}}
color11 #{{YELLOW_BRIGHT}}
color12 #{{BLUE_BRIGHT}}
color13 #{{PRIMARY}}
color14 #{{CYAN_BRIGHT}}
color15 #{{WHITE}}

background_opacity {{KITTY_BG_OPACITY}}

cursor_shape block
cursor_blink_interval 0

symbol_map U+1F300-U+1FAFF Noto Emoji

map ctrl+shift+a>m no_op
map ctrl+shift+a>l no_op
map ctrl+shift+a>1 no_op
map ctrl+shift+a>d no_op
