# ╭──────────────────────────────────────────────────────────────────╮
# │                         Keybinds                                 │
# ╰──────────────────────────────────────────────────────────────────╯

# ─────────────────────────────────────────
# App Variables
# ─────────────────────────────────────────
$terminal    = kitty tmux new-session
$browser     = env -u MOZ_ENABLE_WAYLAND -u LIBVA_DRIVER_NAME -u GBM_BACKEND -u WLR_NO_HARDWARE_CURSORS firefox
$fileManager = yazi
$menu        = env -u WAYLAND_DISPLAY rofi -show drun
$coding      = ~/.local/bin/cursor
$music       = spotify
$chat        = discord

$mainMod = ALT

# ─────────────────────────────────────────
# Applications
# ─────────────────────────────────────────
bind = $mainMod,       RETURN, exec, $terminal
bind = $mainMod,       F,      exec, $browser
bind = $mainMod SHIFT, C,      exec, $coding
bind = $mainMod SHIFT, D,      exec, $menu
bind = $mainMod SHIFT, S,      togglespecialworkspace, music
bind = $mainMod SHIFT, V,      exec, steam
bind = $mainMod SHIFT, Y,      exec, ~/.config/launchers/toggle/toggle_yazi.sh
bind = $mainMod SHIFT, B,      exec, ~/.config/launchers/toggle/toggle_btop.sh
bind = $mainMod SHIFT, I,      exec, $chat
bind = $mainMod SHIFT, O,      exec, ~/.config/hypr/scripts/screenshot.sh
bind = $mainMod SHIFT, L,      exec, ~/.config/hypr/scripts/toggle_dpms.sh
bind = $mainMod,       B,      exec, killall -SIGUSR1 waybar

# ─────────────────────────────────────────
# Window Management
# ─────────────────────────────────────────
bind = $mainMod,       P, pin
bind = $mainMod,       S, togglesplit
bind = $mainMod SHIFT, Q, killactive
bind = $mainMod SHIFT, G, togglefloating
bind = $mainMod SHIFT, R, exec, hyprctl reload

# ─────────────────────────────────────────
# Window Focus
# ─────────────────────────────────────────
bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r

bind = $mainMod,       Tab, cyclenext
bind = $mainMod SHIFT, Tab, cyclenext, prev

# ─────────────────────────────────────────
# Workspaces
# ─────────────────────────────────────────
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# ─────────────────────────────────────────
# Mouse
# ─────────────────────────────────────────
bind  = $mainMod, mouse_down, workspace, e+1
bind  = $mainMod, mouse_up,   workspace, e-1
bindm = $mainMod, mouse:272,  movewindow
bindm = $mainMod, mouse:273,  resizewindow
