# ─── Scratchpads ─────────────────────────────

# Yazi
windowrule = float, class:^(yazi)$
windowrule = size 1500 900, class:^(yazi)$
windowrule = center, class:^(yazi)$
windowrule = noborder, class:^(yazi)$
windowrule = workspace special:yazi silent, class:^(yazi)$

# ncspot
windowrule = workspace special:music silent, class:^(ncspot)$
windowrule = float, class:^(ncspot)$
windowrule = center, class:^(ncspot)$
windowrule = size 1500 900, class:^(ncspot)$

# btop
windowrule = workspace special:btopterm silent, class:^(btopterm)$
windowrule = float, class:^(btopterm)$
windowrule = size 1400 1000, class:^(btopterm)$

# terminal waifus
windowrule = float,class:^(waifu)$
windowrule = workspace special silent,class:^(waifu)$
windowrule = size 2000 1400,class:^(waifu)$
windowrule = center,class:^(waifu)$
