#!/usr/bin/env bash
# fox-monitor-watch — react to monitor hot-swap (dock/undock).
#
# Listens on Hyprland's socket2 for monitoradded / monitorremoved events.
# On change:
#   1. Re-derive MONITOR_RESOLUTIONS, PORTRAIT_OUTPUTS, SECONDARY_OUTPUTS
#      from `hyprctl monitors -j`. PRIMARY is preserved from the existing
#      sidecar — the user's choice from configure_monitors is sticky.
#   2. Update ~/.config/foxml/monitor-layout.conf in place.
#   3. Re-run _generate_per_monitor_wallpapers, _personalize_hyprlock,
#      _personalize_workspace_rules from mappings.sh.
#   4. Fire rotate_wallpaper.sh so awww applies the matching variants.
#
# Hot-swap events fire in bursts (4-6 within ~1s on dock connect). A 2s
# debounce window coalesces them into one re-render.
#
# Idempotent — repeated firing with no actual change is a cheap no-op.

set -u

FOXML_DIR="${FOXML_DIR:-$HOME/code/Linux_Theme}"
SIDECAR="$HOME/.config/foxml/monitor-layout.conf"
SOCKET="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/hypr/${HYPRLAND_INSTANCE_SIGNATURE:-}/.socket2.sock"
DEBOUNCE_SECONDS=2

if [[ ! -S "$SOCKET" ]]; then
    echo "fox-monitor-watch: no Hyprland socket at $SOCKET" >&2
    exit 1
fi
command -v socat   >/dev/null 2>&1 || { echo "fox-monitor-watch: socat required"      >&2; exit 1; }
command -v hyprctl >/dev/null 2>&1 || { echo "fox-monitor-watch: hyprctl required"    >&2; exit 1; }
command -v jq      >/dev/null 2>&1 || { echo "fox-monitor-watch: jq required"         >&2; exit 1; }
if [[ ! -f "$FOXML_DIR/mappings.sh" ]]; then
    echo "fox-monitor-watch: mappings.sh not found at $FOXML_DIR — set FOXML_DIR" >&2
    exit 1
fi

# Re-derive sidecar fields from current hyprctl state. Effective WxH
# accounts for transform (1/3 = 90°/270° → swap). PRIMARY is preserved
# from the existing sidecar so the user's pick from configure_monitors
# isn't clobbered by hot-swap.
rederive_sidecar() {
    local primary=""
    if [[ -f "$SIDECAR" ]]; then
        primary=$(awk -F'"' '/^PRIMARY=/{print $2; exit}' "$SIDECAR")
    fi

    local monitors_json
    monitors_json=$(hyprctl monitors -j 2>/dev/null) || return 1
    [[ -z "$monitors_json" || "$monitors_json" == "[]" ]] && return 1

    # If the recorded PRIMARY is no longer present (e.g. external died and
    # external was the primary), fall back to whatever Hyprland reports
    # first. Keeps the sidecar self-consistent rather than referencing a
    # ghost monitor.
    if [[ -z "$primary" ]] || ! echo "$monitors_json" | jq -e --arg p "$primary" '.[] | select(.name==$p)' >/dev/null; then
        primary=$(echo "$monitors_json" | jq -r '.[0].name')
    fi

    local resolutions portrait secondary
    resolutions=$(echo "$monitors_json" | jq -r '
        .[] |
        if (.transform == 1 or .transform == 3)
        then "\(.name):\(.height)x\(.width)"
        else "\(.name):\(.width)x\(.height)"
        end' | tr '\n' ' ' | sed 's/ *$//')
    portrait=$(echo "$monitors_json" | jq -r '
        .[] | select(.transform == 1 or .transform == 3) | .name
    ' | tr '\n' ' ' | sed 's/ *$//')
    secondary=$(echo "$monitors_json" | jq -r --arg p "$primary" '
        .[] | select(.name != $p) | .name
    ' | tr '\n' ' ' | sed 's/ *$//')

    mkdir -p "$(dirname "$SIDECAR")"
    {
        echo "# Auto-generated by fox-monitor-watch (hot-swap)"
        echo "PRIMARY=\"${primary}\""
        echo "PORTRAIT_OUTPUTS=\"${portrait}\""
        echo "SECONDARY_OUTPUTS=\"${secondary}\""
        echo "MONITOR_RESOLUTIONS=\"${resolutions}\""
    } > "$SIDECAR"
}

apply_changes() {
    # Source mappings.sh fresh each time so any installer-side updates
    # to the personalize helpers are picked up without restarting the
    # listener.
    # shellcheck disable=SC1090
    source "$FOXML_DIR/mappings.sh" 2>/dev/null || return 1

    rederive_sidecar || return 1
    _generate_per_monitor_wallpapers || true
    _personalize_hyprlock            || true
    _personalize_workspace_rules     || true
    if [[ -x "$HOME/.config/hypr/scripts/rotate_wallpaper.sh" ]]; then
        "$HOME/.config/hypr/scripts/rotate_wallpaper.sh" || true
    fi
}

# Coalesce burst events into one re-render. read -t blocks waiting for
# the next event; after the first event fires, we keep draining the
# socket for DEBOUNCE_SECONDS, then apply once.
last_apply_pid=""
debounce_dispatch() {
    # Kill any pending apply — the new event supersedes it.
    if [[ -n "$last_apply_pid" ]] && kill -0 "$last_apply_pid" 2>/dev/null; then
        kill "$last_apply_pid" 2>/dev/null || true
    fi
    (
        sleep "$DEBOUNCE_SECONDS"
        apply_changes
    ) &
    last_apply_pid=$!
}

# socat streams socket2 events line-by-line (event>>payload). We care
# about monitor enumeration changes only — workspace/focus/etc. firehose
# past silently.
# -u = unidirectional. Same systemd-stdin-EOF bug as fox-workspace-color-watch.
socat -u UNIX-CONNECT:"$SOCKET" - 2>/dev/null | while IFS= read -r line; do
    case "$line" in
        monitoradded*|monitorremoved*|monitoraddedv2*)
            debounce_dispatch
            ;;
    esac
done
