#pragma once

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#include <vector>
#include <cmath>
#include <algorithm>
#include <random>
#include <iomanip>
#include <sstream>

namespace foxml {

struct Color {
    uint8_t r, g, b;

    double distance(const Color& other) const {
        return std::sqrt(std::pow(r - other.r, 2) + std::pow(g - other.g, 2) + std::pow(b - other.b, 2));
    }

    std::string toHex() const {
        std::stringstream ss;
        ss << std::hex << std::setw(2) << std::setfill('0') << (int)r
           << std::hex << std::setw(2) << std::setfill('0') << (int)g
           << std::hex << std::setw(2) << std::setfill('0') << (int)b;
        return ss.str();
    }

    double luminance() const {
        return 0.2126 * r + 0.7152 * g + 0.0722 * b;
    }
};

class Generator {
public:
    static void generate(const std::string& image_path, const std::string& output_path) {
        int width, height, channels;
        unsigned char* data = stbi_load(image_path.c_str(), &width, &height, &channels, 3);
        if (!data) throw std::runtime_error("Failed to load image: " + image_path);

        std::vector<Color> pixels;
        pixels.reserve(width * height);
        // Subsample for speed
        for (int i = 0; i < width * height; i += 10) {
            pixels.push_back({data[i*3], data[i*3+1], data[i*3+2]});
        }
        stbi_image_free(data);

        // K-Means clustering
        int k = 8;
        std::vector<Color> centroids = kMeans(pixels, k);
        
        // Sort by luminance
        std::sort(centroids.begin(), centroids.end(), [](const Color& a, const Color& b) {
            return a.luminance() < b.luminance();
        });

        // Semantic mapping (simplified)
        std::map<std::string, std::string> palette;
        palette["BG"] = centroids[0].toHex();
        palette["BG_DARK"] = centroids[0].toHex(); // Could darken manually
        palette["FG"] = centroids[7].toHex();
        palette["PRIMARY"] = centroids[5].toHex();
        palette["SECONDARY"] = centroids[4].toHex();
        palette["ACCENT"] = centroids[3].toHex();
        palette["SURFACE"] = centroids[1].toHex();

        // Write to palette.sh
        std::ofstream out(output_path);
        out << "#!/bin/bash\n# Generated by FoxML Gen from " << image_path << "\n\n";
        for (const auto& [key, value] : palette) {
            out << key << "=" << value << "\n";
        }
        std::cout << "✓ Generated palette.sh at " << output_path << std::endl;
    }

private:
    static std::vector<Color> kMeans(const std::vector<Color>& pixels, int k) {
        std::vector<Color> centroids;
        std::mt19937 rng(1337);
        std::uniform_int_distribution<int> dist(0, pixels.size() - 1);
        
        for (int i = 0; i < k; ++i) centroids.push_back(pixels[dist(rng)]);

        for (int iter = 0; iter < 10; ++iter) {
            std::vector<std::vector<Color>> clusters(k);
            for (const auto& p : pixels) {
                int best_idx = 0;
                double best_dist = p.distance(centroids[0]);
                for (int i = 1; i < k; ++i) {
                    double d = p.distance(centroids[i]);
                    if (d < best_dist) {
                        best_dist = d;
                        best_idx = i;
                    }
                }
                clusters[best_idx].push_back(p);
            }

            for (int i = 0; i < k; ++i) {
                if (clusters[i].empty()) continue;
                long r = 0, g = 0, b = 0;
                for (const auto& p : clusters[i]) {
                    r += p.r; g += p.g; b += p.b;
                }
                centroids[i] = {(uint8_t)(r / clusters[i].size()), (uint8_t)(g / clusters[i].size()), (uint8_t)(b / clusters[i].size())};
            }
        }
        return centroids;
    }
};

} // namespace foxml
