// modules/monitors.cpp — multi-monitor Hyprland layout (native port).
//
// Mirrors mappings.sh:configure_monitors line-by-line:
//   1. hyprctl monitors -j → JSON array of monitor objects.
//   2. Single-monitor path writes minimal sidecar, runs personalize, returns.
//   3. Multi-monitor path: pick primary (eDP-* preferred → interactive →
//      first), TTY-gated y/n to enter interactive layout, primary scale,
//      then per-external: anchor / position / orientation / scale.
//   4. Logical bounds tracked per monitor so subsequent externals can
//      anchor to any already-placed monitor, not just primary.
//   5. Writes ~/.config/hypr/modules/monitors.conf + monitor-layout.conf.
//   6. Calls personalize::apply_all() (same trio configure_monitors did).

#include "../core/context.hpp"
#include "../core/shell.hpp"
#include "../core/sidecar.hpp"
#include "../core/ui.hpp"
#include "personalize.hpp"

#include "../../fox-intel/json.hpp"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <unistd.h>
#include <unordered_map>
#include <vector>

namespace fs = std::filesystem;
using json   = nlohmann::json;

namespace fox_install {

namespace {

bool have(const std::string& bin) {
    std::string out;
    return sh::capture({"sh", "-c", "command -v " + bin}, out) && !out.empty();
}

struct Anchor {
    int x, y, w, h;
};

// (scale_string, scale_x100). Defaults to ("1", 100) under --yes/no-TTY.
std::pair<std::string, int> pick_scale(bool tty) {
    if (!tty) return {"1", 100};
    std::cerr << "    Scale (HiDPI):\n"
                 "      [1] 1x   [2] 1.25x   [3] 1.5x   [4] 2x\n"
                 "    Choice [1]: ";
    std::string line;
    std::getline(std::cin, line);
    if (line == "2") return {"1.25", 125};
    if (line == "3") return {"1.5",  150};
    if (line == "4") return {"2",    200};
    return {"1", 100};
}

int read_int_or(const std::string& line, int fallback) {
    try { return std::stoi(line); } catch (...) { return fallback; }
}

std::string capture_json(const std::vector<std::string>& argv) {
    std::string out;
    if (!sh::capture(argv, out)) return {};
    return out;
}

void write_atomic(const fs::path& dest, const std::string& body) {
    fs::create_directories(dest.parent_path());
    fs::path tmp = dest;
    tmp += ".foxin.tmp";
    {
        std::ofstream w(tmp);
        w << body;
    }
    std::error_code ec;
    fs::rename(tmp, dest, ec);
    if (ec) fs::remove(tmp);
}

void write_sidecar(const fs::path& layout_path,
                   const std::string& primary,
                   const std::string& portrait_outputs,
                   const std::string& secondary_outputs,
                   const std::string& monitor_resolutions) {
    std::ostringstream o;
    o << "# Auto-generated by fox-install --monitors\n"
      << "PRIMARY=\""             << primary             << "\"\n"
      << "PORTRAIT_OUTPUTS=\""    << portrait_outputs    << "\"\n"
      << "SECONDARY_OUTPUTS=\""   << secondary_outputs   << "\"\n"
      << "MONITOR_RESOLUTIONS=\"" << monitor_resolutions << "\"\n";
    write_atomic(layout_path, o.str());
}

void write_monitors_conf(const fs::path& conf,
                         const std::string& primary, const std::string& primary_scale,
                         const std::string& external_rules) {
    std::ostringstream o;
    o << "# ╭──────────────────────────────────────────────────────────────────╮\n"
         "# │                          Monitors                                │\n"
         "# ╰──────────────────────────────────────────────────────────────────╯\n"
         "# Generated by fox-install --monitors — re-run to reconfigure.\n"
         "# Per-monitor rules below; if a monitor is unplugged, Hyprland\n"
         "# silently ignores its rule. The catch-all at the bottom handles\n"
         "# unknown displays at runtime.\n"
         "\n"
      << "monitor = " << primary << ", preferred, 0x0, " << primary_scale << "\n"
      << external_rules
      << "\n"
         "# Catch-all for any unknown/disconnected displays at runtime\n"
         "monitor = , preferred, auto, 1\n";
    write_atomic(conf, o.str());
}

}  // namespace

void run_monitors(Context& ctx) {
    ui::section("Configuring Hyprland monitor layout");

    // Dry-run short-circuit. The interactive multi-monitor branch writes
    // monitors.conf + sidecar via direct std::ofstream (not via sh::),
    // so a TTY-attached --dry-run would still clobber real files.
    if (sh::dry_run()) {
        ui::substep("[dry-run] would: parse `hyprctl monitors -j`, prompt "
                    "for primary/position/orientation/scale, write "
                    "~/.config/hypr/modules/monitors.conf + "
                    "~/.config/foxml/monitor-layout.conf");
        return;
    }

    if (!have("hyprctl")) {
        ui::warn("hyprctl not on PATH — Hyprland not running? Skipping monitor setup");
        return;
    }

    std::string raw = capture_json({"hyprctl", "monitors", "-j"});
    if (raw.empty()) {
        ui::warn("Hyprland not running — skipping (re-run inside a Hyprland session)");
        return;
    }
    json monitors;
    try {
        monitors = json::parse(raw);
    } catch (const std::exception& e) {
        ui::err(std::string("hyprctl monitors -j parse failed: ") + e.what());
        return;
    }
    if (!monitors.is_array()) {
        ui::err("unexpected hyprctl output shape");
        return;
    }

    fs::path layout_path = ctx.config_home / "foxml/monitor-layout.conf";
    fs::path monitors_conf = ctx.config_home / "hypr/modules/monitors.conf";

    const std::size_t count = monitors.size();
    if (count <= 1) {
        // Single-monitor path — clear any stale layout from a previous dock.
        std::string name = monitors.empty() ? "" :
            monitors[0].value("name", "");
        int w = monitors.empty() ? 0 : monitors[0].value("width",  0);
        int h = monitors.empty() ? 0 : monitors[0].value("height", 0);
        if (!name.empty() && w > 0 && h > 0) {
            write_sidecar(layout_path, name, "", "",
                          name + ":" + std::to_string(w) + "x" + std::to_string(h));
            auto layout = sidecar::read(layout_path);
            personalize::apply_all(ctx, layout);
        } else {
            write_sidecar(layout_path, name, "", "", "");
            auto layout = sidecar::read(layout_path);
            personalize::personalize_workspace_rules(ctx, layout);
        }
        ui::ok("single-monitor layout written");
        return;
    }

    std::printf("\n"
        "╭──────────────────────────────────────────────────────────────────╮\n"
        "│   Multi-Monitor Setup                                            │\n"
        "├──────────────────────────────────────────────────────────────────┤\n"
        "│   Detected %zu monitors:                                          \n",
        count);
    for (auto& m : monitors) {
        std::printf("│     • %s  %dx%d  — %s\n",
            m.value("name", "?").c_str(),
            m.value("width", 0), m.value("height", 0),
            m.value("description", "").c_str());
    }
    std::printf("╰──────────────────────────────────────────────────────────────────╯\n");

    // Primary picker: prefer eDP-* (laptop panel), else prompt, else first.
    std::string primary;
    for (auto& m : monitors) {
        std::string n = m.value("name", "");
        if (n.rfind("eDP", 0) == 0) { primary = n; break; }
    }
    const bool tty_in = ::isatty(STDIN_FILENO);
    if (primary.empty() && tty_in) {
        std::cout << "\n  No laptop panel detected — pick a primary monitor:\n";
        std::vector<std::string> all_names;
        int i = 1;
        for (auto& m : monitors) {
            std::string n  = m.value("name", "");
            int        w  = m.value("width", 0);
            int        h  = m.value("height", 0);
            all_names.push_back(n);
            std::printf("    [%d] %s  (%dx%d)\n", i++, n.c_str(), w, h);
        }
        std::cout << "    Choice [1]: " << std::flush;
        std::string line;
        std::getline(std::cin, line);
        int pick = read_int_or(line, 1);
        if (pick < 1 || pick > static_cast<int>(all_names.size())) pick = 1;
        primary = all_names[pick - 1];
    }
    if (primary.empty()) primary = monitors[0].value("name", "");

    // TTY-gated y/n. No sensible auto-default for layout; under no-TTY,
    // bail out so we don't clobber an existing monitors.conf.
    if (tty_in) {
        std::cout << "Configure layout interactively? [y/N] " << std::flush;
        std::string line;
        std::getline(std::cin, line);
        if (line.empty() || (line[0] != 'y' && line[0] != 'Y')) {
            ui::ok("Skipping — current monitors.conf left as-is");
            return;
        }
    } else {
        ui::warn("no TTY — skipping interactive layout (run interactively to configure)");
        return;
    }

    // Primary dimensions + scale.
    int primary_w = 0, primary_h = 0;
    for (auto& m : monitors) {
        if (m.value("name", "") == primary) {
            primary_w = m.value("width", 0);
            primary_h = m.value("height", 0);
            break;
        }
    }
    std::cout << "\n  Primary: " << primary << "  ("
              << primary_w << "x" << primary_h << ")\n";
    auto [primary_scale, primary_scale_x100] = pick_scale(tty_in);
    int primary_logical_w = primary_w * 100 / primary_scale_x100;
    int primary_logical_h = primary_h * 100 / primary_scale_x100;

    std::unordered_map<std::string, Anchor> anchors;
    anchors[primary] = {0, 0, primary_logical_w, primary_logical_h};
    std::vector<std::string> placed = {primary};

    std::ostringstream rules;
    std::string portrait_outputs, secondary_outputs;
    std::ostringstream monitor_resolutions;
    monitor_resolutions << primary << ":" << primary_w << "x" << primary_h;

    for (auto& m : monitors) {
        std::string ext = m.value("name", "");
        if (ext.empty() || ext == primary) continue;
        int ext_w = m.value("width",  0);
        int ext_h = m.value("height", 0);

        std::string pos = "right", orient = "landscape", anchor_name = primary;

        std::cout << "\n  External: " << ext << "  ("
                  << ext_w << "x" << ext_h << ")\n";

        if (placed.size() > 1) {
            std::cout << "    Position relative to which monitor:\n";
            int i = 1;
            for (auto& cand : placed) {
                std::cout << "      [" << i++ << "] " << cand
                          << (cand == primary ? " (primary)" : "") << "\n";
            }
            std::cout << "    Choice [1]: " << std::flush;
            std::string line;
            std::getline(std::cin, line);
            int pick = read_int_or(line, 1);
            if (pick >= 1 && pick <= static_cast<int>(placed.size())) {
                anchor_name = placed[pick - 1];
            }
        }

        std::cout << "    Position relative to " << anchor_name << ":\n"
                     "      [1] left   [2] right   [3] above   [4] below\n"
                     "    Choice [2]: " << std::flush;
        {
            std::string line;
            std::getline(std::cin, line);
            if      (line == "1") pos = "left";
            else if (line == "3") pos = "above";
            else if (line == "4") pos = "below";
            else                  pos = "right";
        }

        std::cout << "    Orientation:\n"
                     "      [1] landscape   [2] portrait, rotated left   [3] portrait, rotated right\n"
                     "    Choice [1]: " << std::flush;
        {
            std::string line;
            std::getline(std::cin, line);
            if      (line == "2") orient = "portrait-left";
            else if (line == "3") orient = "portrait-right";
            else                  orient = "landscape";
        }

        auto [ext_scale, ext_scale_x100] = pick_scale(tty_in);

        // Post-transform physical dimensions + logical (post-scale) bounds.
        int phys_w = ext_w, phys_h = ext_h;
        int eff_w  = ext_w, eff_h  = ext_h, transform = 0;
        if (orient == "portrait-left")  { eff_w = ext_h; eff_h = ext_w; transform = 3; }
        if (orient == "portrait-right") { eff_w = ext_h; eff_h = ext_w; transform = 1; }
        if (transform != 0) { phys_w = ext_h; phys_h = ext_w; }
        eff_w = eff_w * 100 / ext_scale_x100;
        eff_h = eff_h * 100 / ext_scale_x100;

        const Anchor& a = anchors[anchor_name];
        int ext_x = 0, ext_y = 0;
        if      (pos == "right") { ext_x = a.x + a.w;          ext_y = a.y + (a.h - eff_h) / 2; }
        else if (pos == "left")  { ext_x = a.x - eff_w;        ext_y = a.y + (a.h - eff_h) / 2; }
        else if (pos == "above") { ext_x = a.x + (a.w - eff_w) / 2; ext_y = a.y - eff_h; }
        else if (pos == "below") { ext_x = a.x + (a.w - eff_w) / 2; ext_y = a.y + a.h;  }

        if (transform != 0) {
            rules << "monitor = " << ext << ", preferred, "
                  << ext_x << "x" << ext_y << ", " << ext_scale
                  << ", transform, " << transform << "\n";
            portrait_outputs += ext + " ";
        } else {
            rules << "monitor = " << ext << ", preferred, "
                  << ext_x << "x" << ext_y << ", " << ext_scale << "\n";
        }
        secondary_outputs   += ext + " ";
        monitor_resolutions << " " << ext << ":" << phys_w << "x" << phys_h;

        anchors[ext] = {ext_x, ext_y, eff_w, eff_h};
        placed.push_back(ext);
    }

    // Trim trailing spaces — matches bash `${portrait_outputs% }`.
    while (!portrait_outputs.empty() && portrait_outputs.back() == ' ')
        portrait_outputs.pop_back();
    while (!secondary_outputs.empty() && secondary_outputs.back() == ' ')
        secondary_outputs.pop_back();

    write_monitors_conf(monitors_conf, primary, primary_scale, rules.str());
    write_sidecar(layout_path, primary, portrait_outputs, secondary_outputs,
                  monitor_resolutions.str());

    ui::ok("monitors.conf written (" + monitors_conf.string() + ")");
    ui::ok("layout sidecar       (" + layout_path.string() + ")");

    auto layout = sidecar::read(layout_path);
    personalize::apply_all(ctx, layout);
}

}  // namespace fox_install
